### ISSUE TITLE
[Feat request] expose a way to hide PDCurses menu

### ISSUE THREAD

**Issue by Geobert** [ihalila/pancurses#17]
I'd like to hide the menu with "Font" and "Paste" entries.

Maybe by exposing https://github.com/Bill-Gray/PDCurses/blob/18404de78edbc62220899a60902d3f3b44759d86/win32a/pdcscrn.c#L1740

**Comment by lnicola** [comment]
Beware:

```c
#ifdef _MSC_VER
#define INLINE static
#else
#define INLINE static inline
#endif
```

It would probably be better either to expose `PDC_hWnd` and add some helper methods for additional functionality or implement this directly in PDCurses.

**Comment by ihalila** [comment]
This is a bit of a pain until https://github.com/Bill-Gray/PDCurses/issues/44 is resolved. It would be best to patch in a way to do this into PDCurses instead of adding workarounds to pancurses.

Allowing you to enable/disable the menu before calling initscr() should be pretty easy though, but toggling it afterwards will not be so easy. Is that enough for your usecase?

**Comment by Geobert** [comment]
Yes, my app do not need this menu :)

**Comment by ihalila** [comment]
v0.13 of pancurses now disables the menu by default (it remains available by right-clicking the titlebar). You can revert to the old behaviour with the "show_menu" cargo feature.
