### ISSUE TITLE
Support resizable window on Windows

### ISSUE THREAD

**Issue by coder543** [ihalila/pancurses#20]
On Windows, the pdcurses window is created with a fixed height and width, and there appears to be no way for the user to resize the window or for the programmer to do so.

[from the log over here:](https://www.projectpluto.com/win32a.htm)

![screenshot-2017-10-24 pdcurses log](https://user-images.githubusercontent.com/726063/31978035-83f1b728-b90d-11e7-8b44-ae1d6e0c90fb.png)

It would be nice if the `PDC_set_resize_limits` function were either called directly from the initscr() function, setting effectively unlimited resize limits so that terminals would have the same expectation of resizability on Windows that they do on Linux, or if it were exposed directly through `pancurses` somehow so a programmer could invoke it. I guess I could always invoke it through `pdcurses-sys` directly, of course.

**Comment by ihalila** [comment]
I did a quick test of this and PDC_set_resize_limits() doesn't seem to have any noticeable effect, it didn't allow resizing the window by dragging its edges. I'll need to look into it some more to see where the issue is.

**Comment by ihalila** [comment]
Okay it's something in the way I did it, manually modifying the registry value PDCurses uses to store the limits enabled resizing.

**Comment by ihalila** [comment]
This turned out to be a bit trickier than I expected. The problem with PDC_set_resize_limits() is that it only affects things if called on the first run of an app. PDCurses automatically stores the resize limits into the Windows registry, and if it finds them from there it uses whatever is stored there and ignores later calls to PDC_set_resize_limits.

In practice this means that PDC_set_resize_limits isn't really usable, so instead pancurses now automatically sets the registry values to allow unlimited resizing of the window. You can disable this behaviour with the feature flag "disable_resize".
